version: '3.8'

services:
  target-jdk8:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-target-jdk8
    ports:
      - "8080:8080"
      - "9090:9090"
    networks:
      - testnet
    restart: unless-stopped

  target-jdk7:
    build:
      context: .
      dockerfile: Dockerfile.jdk7
    container_name: test-target-jdk7
    ports:
      - "8081:8081"
    networks:
      - testnet
    restart: unless-stopped

networks:
  testnet:
    driver: bridge
